2018-05-15 18:04:26,600 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:06:29,784 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:06:45,958 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:06:50,520 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host http:80 ssl:False [getaddrinfo failed] Index:1 URL:http://http://127.0.0.1:9000/
2018-05-15 18:07:40,075 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:07:44,636 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host http:80 ssl:False [getaddrinfo failed] Index:1 URL:http://http://127.0.0.1:9000/
2018-05-15 18:08:11,237 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:08:15,735 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host http:80 ssl:False [getaddrinfo failed] Index:1 URL:http://http://localhost:9000/
2018-05-15 18:08:47,419 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:09:05,204 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:09:07,629 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:30 URL:http://localhost:9000/
2018-05-15 18:09:07,630 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:16 URL:http://localhost:9000/
2018-05-15 18:09:07,630 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:41 URL:http://localhost:9000/
2018-05-15 18:09:07,631 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:7 URL:http://localhost:9000/
2018-05-15 18:09:07,631 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:3 URL:http://localhost:9000/
2018-05-15 18:09:07,631 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:21 URL:http://localhost:9000/
2018-05-15 18:09:07,631 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:19 URL:http://localhost:9000/
2018-05-15 18:09:07,631 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:37 URL:http://localhost:9000/
2018-05-15 18:09:21,710 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:14:52,293 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:15:14,572 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:15:46,693 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:16:13,909 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:8210 URL:http://localhost:9000/
2018-05-15 18:16:41,897 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:16:42,956 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:8 URL:http://localhost:9000/
2018-05-15 18:16:45,236 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-15 18:16:46,251 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:2 URL:http://localhost:9000/
2018-05-16 16:03:11,114 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-16 16:03:13,215 pure_coroutine1.1.py [line:26 INFO Exception:Cannot connect to host localhost:9000 ssl:False [Connect call failed ('::1', 9000)] Index:1 URL:http://localhost:9000/
2018-05-16 16:03:32,165 pure_coroutine1.1.py [line:26 INFO *************************Start url count:10000*************************
2018-05-16 16:04:11,316 pure_coroutine1.1.py [line:26 INFO *************************END*************************
